### ISSUE TITLE
NullPointerException at addItem() at StealTask

### ISSUE THREAD

**Issue by emlai** [emlai/wge3#23]
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at wge3.model.Inventory.addItem(Inventory.java:55)
	at wge3.model.ai.StealTask.execute(StealTask.java:41)
	at wge3.model.ai.ThiefAI.update(ThiefAI.java:46)
	at wge3.model.NonPlayer.updateAI(NonPlayer.java:26)
	at wge3.engine.PlayState.update(PlayState.java:68)
	at wge3.engine.GameStateManager.update(GameStateManager.java:57)
	at wge3.engine.WGE3.render(WGE3.java:29)
```

**Comment by emlai** [comment]
Not yet fixed.
